### PR TITLE
Updated classic classes 7e to 3e

### PR DESCRIPTION
**Pull request by Felix3qH4**
- Renamed all 'M' classes from 7e to 3e to 'C' classes as it seems that the 'C' classes were called 'M' classes a few years ago
- Renamed all 'C' classes from 7e to 3e to 'CL' classes as it seems that the Latin classes were called 'C' classes a few years ago
- Renamed the following classes:
- 7e to 7C     *
- 6C to 6CL
- 5C to 5CL
- 4C to 4CL
- 3CA to 3CLA
- 3MA to 3CA
- 3CB to 3CLB
- 3MB to 3CB
- 3CC to 3CLC
- 3MC to 3CC
- 3CD to 3CLD
- 3MD to 3CD
- 3CE to 3CLE
- 3ME to 3CE
- 3CF to 3CLF
- 3MF to 3CF
- 3MG to 3CG
- 3MG which should have been 3CG to 3CLG (3MG was there twice but one with Latin and one without)
- 3I to 3CI

### CODE REVIEW

**Comment by Felix3qH4** [comment]
Added the following classes:

- 6C, 6CZH
- 5C, 5CZH
- 4C, 4CZH
- 3CLI, 3CZHI

**Comment by Felix3qH4** [comment]
Changed:

- added 4e langue to 3CA (now renamed to 3CLA)
- changed EduMusic to a combination of 4 lessons with different coefficients in all 3F classes, same for Artistique

**Comment by Felix3qH4** [comment]
@Krecharles is it possible to write coefficients as fractions?
For example the 3F classes have the lesson EduMusic with coefficient 4.
It is composed of 4 lessons:
- HisMu 2/6
- TheFo 2/6
- ChaCh 1/6
- PraIn  1/6

Can one write the coefficient like follows in the excel or won't that work later on for the calculation in the app?
HisMu 4*(2/6)
ChaCh 4*(1/6)

**Comment by Felix3qH4** [comment]
Fixed typos (ex. Francais instead of Français or Conmon instead of ConMon)
Added 5C-AD and 4C-AD
Removed luxembourgish lesson from 7ème classes as its no longer in the official plan #51

**Comment by Krecharles** [comment]
Hey, thanks for your work!

What you are describing is a feature i called combi subjects. For example, the numbers on in the red column indicate the relative proportion of “Dessin”, “Graphisme” and “HistoArt” with respect to their sum, ie 1 / (1 + 1 + 1) in the 3 cases.
image

I think it is also important for you to know that i’m currently reworking Datz in Flutter because this code is really outdated and to an added benefit would be an android app. I don’t really plan to release an update for the current xcode version, but changes to the classes will ofc reflect in the flutter version. You can check it out here: https://github.com/Krecharles/datz_flutter

As a side note, i also plan to add an error reporting feature into the app to make it easier to maintain this classes database.

I will merge this pull request in a week or so, as i see you are still actively working on it

**Comment by Felix3qH4** [comment]
That's exactly what I was referencing, the combi subjects.
I just started a few days ago with flutter with the goal to 1) learn flutter and 2) rewrite an android version of the Datz! app because I find it very nicely designed and built but I'm more of an android user and I always wanted to have it on android too.
So if you want I can help there too, but I just started with flutter so I only know the basics.

The error reporting feature is a great idea, as that way people don't have to go to github, create an account and then finally post their issue. That way more people will probably report issues about the app or missing classes, etc.

I also started standardizing lesson names in a file, so that there are not 5 different names for the same lesson in the App.
The file is looking like this:
image
So in the future when there is a long name like the last one in the picture, one can just look up the abbreviation used everywhere in the app.

**Comment by Krecharles** [comment]
Your file is a good idea, that could be really helpful!

**Pull request closed without merging**
